// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package model

func checkResetMethod(s interface{}) (interface{ Reset() }, bool) {
	meth, ok := s.(interface{ Reset() })
	return meth, ok
}

func (rs *MetricaCounter) Reset() {
	if rs == nil {
		return
	}
	rs.name = ""
	// rs.kind=nil //UNKNOWN TYPE (type KindValue)
	rs.value = 0
	if rs.newValue != nil {
		*rs.newValue = 0
	}
}

func (rs *MetricaGauge) Reset() {
	if rs == nil {
		return
	}
	rs.name = ""
	// rs.kind=nil //UNKNOWN TYPE (type KindValue)
	rs.value = 0.0
	if rs.newValue != nil {
		*rs.newValue = 0.0
	}
}
