// Code generated by MockGen. DO NOT EDIT.
// Source: tcl.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/qesterrx/tplmetrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricaStorage is a mock of MetricaStorage interface.
type MockMetricaStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetricaStorageMockRecorder
}

// MockMetricaStorageMockRecorder is the mock recorder for MockMetricaStorage.
type MockMetricaStorageMockRecorder struct {
	mock *MockMetricaStorage
}

// NewMockMetricaStorage creates a new mock instance.
func NewMockMetricaStorage(ctrl *gomock.Controller) *MockMetricaStorage {
	mock := &MockMetricaStorage{ctrl: ctrl}
	mock.recorder = &MockMetricaStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricaStorage) EXPECT() *MockMetricaStorageMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockMetricaStorage) Check(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockMetricaStorageMockRecorder) Check(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockMetricaStorage)(nil).Check), ctx)
}

// Debug mocks base method.
func (m *MockMetricaStorage) Debug(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", ctx)
}

// Debug indicates an expected call of Debug.
func (mr *MockMetricaStorageMockRecorder) Debug(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockMetricaStorage)(nil).Debug), ctx)
}

// GetAllMetrics mocks base method.
func (m *MockMetricaStorage) GetAllMetrics(ctx context.Context) []model.Metrica {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics", ctx)
	ret0, _ := ret[0].([]model.Metrica)
	return ret0
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockMetricaStorageMockRecorder) GetAllMetrics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockMetricaStorage)(nil).GetAllMetrics), ctx)
}

// GetMetrica mocks base method.
func (m *MockMetricaStorage) GetMetrica(ctx context.Context, name, kind string) (model.Metrica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrica", ctx, name, kind)
	ret0, _ := ret[0].(model.Metrica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrica indicates an expected call of GetMetrica.
func (mr *MockMetricaStorageMockRecorder) GetMetrica(ctx, name, kind interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrica", reflect.TypeOf((*MockMetricaStorage)(nil).GetMetrica), ctx, name, kind)
}

// UpdateMetrica mocks base method.
func (m *MockMetricaStorage) UpdateMetrica(ctx context.Context, mtrk model.Metrica) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrica", ctx, mtrk)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetrica indicates an expected call of UpdateMetrica.
func (mr *MockMetricaStorageMockRecorder) UpdateMetrica(ctx, mtrk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrica", reflect.TypeOf((*MockMetricaStorage)(nil).UpdateMetrica), ctx, mtrk)
}

// UpdateMetricaBatch mocks base method.
func (m *MockMetricaStorage) UpdateMetricaBatch(ctx context.Context, mtrks []model.Metrica) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricaBatch", ctx, mtrks)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetricaBatch indicates an expected call of UpdateMetricaBatch.
func (mr *MockMetricaStorageMockRecorder) UpdateMetricaBatch(ctx, mtrks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricaBatch", reflect.TypeOf((*MockMetricaStorage)(nil).UpdateMetricaBatch), ctx, mtrks)
}

// WriteMetrics mocks base method.
func (m *MockMetricaStorage) WriteMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMetrics indicates an expected call of WriteMetrics.
func (mr *MockMetricaStorageMockRecorder) WriteMetrics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMetrics", reflect.TypeOf((*MockMetricaStorage)(nil).WriteMetrics), ctx)
}

// MockUpdateMetricaSubscriber is a mock of UpdateMetricaSubscriber interface.
type MockUpdateMetricaSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateMetricaSubscriberMockRecorder
}

// MockUpdateMetricaSubscriberMockRecorder is the mock recorder for MockUpdateMetricaSubscriber.
type MockUpdateMetricaSubscriberMockRecorder struct {
	mock *MockUpdateMetricaSubscriber
}

// NewMockUpdateMetricaSubscriber creates a new mock instance.
func NewMockUpdateMetricaSubscriber(ctrl *gomock.Controller) *MockUpdateMetricaSubscriber {
	mock := &MockUpdateMetricaSubscriber{ctrl: ctrl}
	mock.recorder = &MockUpdateMetricaSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateMetricaSubscriber) EXPECT() *MockUpdateMetricaSubscriberMockRecorder {
	return m.recorder
}

// PushNotify mocks base method.
func (m *MockUpdateMetricaSubscriber) PushNotify(ctx context.Context, msg []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushNotify", ctx, msg)
}

// PushNotify indicates an expected call of PushNotify.
func (mr *MockUpdateMetricaSubscriberMockRecorder) PushNotify(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushNotify", reflect.TypeOf((*MockUpdateMetricaSubscriber)(nil).PushNotify), ctx, msg)
}
