// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package service

func checkResetMethod(s interface{}) (interface{ Reset() }, bool) {
	meth, ok := s.(interface{ Reset() })
	return meth, ok
}

func (rs *TCLService) Reset() {
	if rs == nil {
		return
	}
	if resetter, ok := checkResetMethod(rs.config); ok && rs.config != nil {
		resetter.Reset()
	}
	// rs.storage=nil //UNKNOWN TYPE (type MetricaStorage)
	rs.subs = rs.subs[:0]
}
