// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package excample

func checkResetMethod(s interface{}) (interface{ Reset() }, bool) {
	meth, ok := s.(interface{ Reset() })
	return meth, ok
}

func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}
	rs.i = 0
	rs.str = ""
	if rs.strP != nil {
		*rs.strP = ""
	}
	rs.s = rs.s[:0]
	clear(rs.m)
	if resetter, ok := checkResetMethod(rs.child); ok && rs.child != nil {
		resetter.Reset()
	}
}
